<a href="https://colab.research.google.com/github/kkaisar/Data_base/blob/main/firsthw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)  # Matrix multiplication
print(result)

[[19 22]
 [43 50]]


In [ ]:
#2
A = np.array([[1, 2], [3, 4]])
transpose_A = np.transpose(A)
print(transpose_A)


[[1 3]
 [2 4]]


In [ ]:
#3A = np.array([[1, 2], [3, 4]])
inverse_A = np.linalg.inv(A)
print(inverse_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#4
A = np.array([[1, 2], [3, 4]])
determinant_A = np.linalg.det(A)
print(determinant_A)

-2.0000000000000004


In [ ]:
#5
A = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
#calculus

In [ ]:
#6
x = np.array([1, 2, 3, 4, 5])
y = x**2
gradient = np.gradient(y)
print(gradient)

[3. 4. 6. 8. 9.]


In [ ]:
#7
from scipy import integrate
x = np.linspace(0, 10, 100)
y = np.sin(x)
integral = integrate.cumtrapz(y, x, initial=0)


<ipython-input-25-29f886b9a548>:4: DeprecationWarning: 'scipy.integrate.cumtrapz' is deprecated in favour of 'scipy.integrate.cumulative_trapezoid' and will be removed in SciPy 1.14.0
  integral = integrate.cumtrapz(y, x, initial=0)


In [ ]:
#8
y = np.array([1, 4, 9, 16, 25])
derivative_2nd = np.diff(y, n=2)
print(derivative_2nd)
#9
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print(solution)

[2 2 2]
[2. 3.]


In [ ]:
#statistics

In [ ]:
#10
data = np.array([1, 2, 3, 4, 5])
std_deviation = np.std(data)
print(std_deviation)

1.4142135623730951


In [ ]:
#11
data = np.array([1, 2, 3, 4, 5])
variance = np.var(data)
print(variance)

2.0


In [ ]:
#12
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print(mean_value)

3.0
